site_name: Learning UI
nav:
  - Introduction: introduction.md
  - Installation: installation.md
  - Customization Guide: guide.md
  - Packages: packages.md
  - License: license.md
  - Release Notes: release.md
theme: 
  name: material  
  logo: open-book-white.png
  favicon: open-book.png    
  palette:
    primary: red
    accent: cyan
